choco/urls.py
from choco.views import *
from django.urls import path


app_name = 'dairy' 


urlpatterns = [
    
    path('dairy/',dairy , name ='dairy'),
    path('chocolate/',chocolate , name ='chocolate'),
]

project2/urls.py
from django.contrib import admin
from django.urls import path,include

import choco

urlpatterns = [
    path('admin/', admin.site.urls),
    path('choco/',include('choco.urls')),
]

choco/models.py
from django.db import models

# Create your models here.

choco/views.py
from django.shortcuts import render

# Create your views here.
def dairy(request):
    return render(request, 'dairy.html') 

def chocolate(request):
    return render(request, 'chocolate.html')

templates/chocolate.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=3, initial-scale=1.0">
    <title>chocolate</title>
</head>
<body>
    <center>
        <h1> Fruit and nut Filling Wrapped Chocolates - 500 gm Homemade Chocolate</h1>
        <img src="https://www.ubuy.co.in/productimg/?image=aHR0cHM6Ly9pbWFnZXMtY2RuLnVidXkuY28uaW4vNjM0ZDFiNmVhMTZmNTQ3MGIwNjU2NjAxLWNhZGJ1cnktY2hvY29sYXRlLWJhci1zZWxlY3Rpb24tb2YtaXJpc2guanBn.jpg" alt="">
        <h1><a href="{% url 'dairy:dairy' %}">click here for dairy milk</a></h1>
    </center>
</body>
</html>

templates/dairy.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=3, initial-scale=1.0">
    <title>dairy</title>
</head>
<body>
    <center>
        <h1> Cadbury Dairy Milk Silk Chocolate Bar, 60 Gram : Amazon.in: Grocery and Gourmet Foods</h1>
        <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS0efWYdXKODDuIHHa8yGxxaNX5SS617K88Ww&s" alt="">

        <h1><a href="{% url 'dairy:chocolate' %}">click here for chocolate</a></h1>
       
    </center>
</body>
</html>